package:
  name: hydraspa
  version: 0.0.2

source:
  path: .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - docopt
    - numpy
    - scipy
    - pandas

test:
  imports:
    - hydraspa