{% set data = load_setup_py_data() %}

package:
  name: hydraspa
  version: {{ data.get('version') }}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - docopt
    - numpy
    - pandas
    - scipy
    - statsmodels
    - mdanalysis

test:
  imports:
    - hydraspa
  commands:
    - hydraspa -h