package:
  name: hydraspa
  version: 0.0.4

source:
  path: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - docopt
    - numpy
    - pandas
    - scipy
    - statsmodels

test:
  imports:
    - hydraspa